SELECT IN_A.ANIMAL_ID, IN_A.ANIMAL_TYPE, IN_A.NAME
FROM ANIMAL_INS AS IN_A
JOIN ANIMAL_OUTS AS OUT_A ON OUT_A.ANIMAL_ID = IN_A.ANIMAL_ID
WHERE OUT_A.SEX_UPON_OUTCOME != IN_A.SEX_UPON_INTAKE
ORDER BY IN_A.ANIMAL_ID
